version: "3.8"
services:
  py: &py
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    volumes:
      - .:/app
    environment:
      - REDIS_URL=redis://redis:6379/0
      - USER_PRIVATE_KEY
    tty: true
    logging:
      driver: "json-file"
      options:
        max-size: "32m"
    depends_on:
      redis:
        condition: service_started

  redis:
    image: redis:6.2.6
    volumes:
      - './config/redis.conf:/usr/local/etc/redis/redis.conf:ro'

  py-hardhat:
    <<: *py
    environment:
      - REDIS_URL=redis://redis:6379/0
      - USER_PRIVATE_KEY=0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80
      - WEB3_PROVIDER_URI=http://perpdex-hardhat:8545
      - WEB3_NETWORK_NAME=localhost
      - INITIAL_EVENT_BLOCK_NUMBER=0
      - PERPDEX_CONTRACT_ABI_JSON_DIRPATH=/app/hardhat/deployments/localhost/
    depends_on:
      redis:
        condition: service_started
      perpdex-hardhat:
        condition: service_healthy
    
  perpdex-hardhat:
    build:
      context: ./hardhat
      dockerfile: Dockerfile
    volumes:
      - ./hardhat:/app
      - ./deps:/deps
    command: sh -c "yarn install && yarn hardhat node"
    expose:
      - 8545  # hardhat localhost default port
    healthcheck:
      test: curl -f http://localhost:8545 || exit 1
      interval: 3s
      timeout: 5s
      retries: 15
      start_period: 30s

  py-shibuya:
    <<: *py
    environment:
      - REDIS_URL=redis://redis:6379/0
      - INITIAL_EVENT_BLOCK_NUMBER=1627735
      - PERPDEX_CONTRACT_ABI_JSON_DIRPATH=deps/perpdex-contract/deployments/shibuya/
      - USER_PRIVATE_KEY
      - WEB3_PROVIDER_URI=wss://rpc.shibuya.astar.network
      - WEB3_NETWORK_NAME=shibuya
 
