version: "3.8"
services:
  py: &py
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    volumes:
      - .:/app
    environment:
      - USER_PRIVATE_KEY
      - REDIS_URL=redis://redis:6379/0
    tty: true
    logging:
      driver: "json-file"
      options:
        max-size: "32m"
    depends_on:
      redis:
        condition: service_started

  redis:
    image: redis:6.2.6
    volumes:
      - './config/redis.conf:/usr/local/etc/redis/redis.conf:ro'

  py-shibuya:
    <<: *py
    env_file:
      - .env.shibuya
 
 